version: "2.4"

services:
  nodejs:
    build:
      context: ../
    container_name: nodejs-api
    working_dir: /var/www/html
    volumes:
      - ../app:/var/www/html
    ports:
      - 80:8080
    restart: always

  redis:
    image: redis:3.2-alpine
    container_name: nodejs-redis

  dbMysql:
    image: mysql:8.0.3
    container_name: nodejs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - my-dbvolume:/var/lib/mysql

volumes:
  my-dbvolume:
